/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Shahriar Shahrabi (https://sketchfab.com/shahriyarshahrabi)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/house-on-the-hill-3efa0f73228946009b9a8ee885f59165
Title: House on the Hill
*/
import React, { useRef } from 'react'
import { useGLTF, useScroll } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { a } from '@react-spring/three'
import HillHouseScene from '../assets/3d/hillHouse1.glb'

const HillHouse = ({ isRotating, setIsRotating, setCurrentStage, ...props }) => {
  const hillHouseRef = useRef()
  const scroll = useScroll()
  const { nodes, materials } = useGLTF(HillHouseScene)
  const lastStage = useRef(null)

  useFrame(() => {
    // 1. Map scroll progress to rotation (0 to 2*PI)
    const rotationAmount = scroll.offset * Math.PI * 2;
    
    if (hillHouseRef.current) {
      hillHouseRef.current.rotation.y = rotationAmount;
    }

    // 2. Linear Stage Detection
    // Since scroll.offset is always 0 to 1, we divide it into 4 equal sections
    // This ensures they always show up as 1 -> 2 -> 3 -> 4
    const scrollProgress = scroll.offset;
    let newStage = null
    
    if (scrollProgress >= 0.02 && scrollProgress <= 0.22) {
    newStage = 1;
  } else if (scrollProgress >= 0.28 && scrollProgress <= 0.48) {
    newStage = 2;
  } else if (scrollProgress >= 0.52 && scrollProgress <= 0.72) {
    newStage = 3;
  } else if (scrollProgress >= 0.78 && scrollProgress <= 0.98) {
    newStage = 4;
  }

  if (newStage !== lastStage.current) {
    lastStage.current = newStage;
    setCurrentStage(newStage);
  }
});

  
  
  return (
    <a.group ref={hillHouseRef} {...props} >
      <mesh castShadow receiveShadow geometry={nodes.Cube.geometry} material={materials.Material} />
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh castShadow receiveShadow geometry={nodes.Details_AllTogetherBake_0.geometry} material={materials.AllTogetherBake} />
          <mesh castShadow receiveShadow geometry={nodes.Details_AllTogetherBake_0001.geometry} material={materials.AllTogetherBake} />
          <mesh castShadow receiveShadow geometry={nodes.Details_AllTogetherBake_0002.geometry} material={materials.AllTogetherBake} />
          <mesh castShadow receiveShadow geometry={nodes.Details_AllTogetherBake_0003.geometry} material={materials.AllTogetherBake} />
          <mesh castShadow receiveShadow geometry={nodes.Details_AllTogetherBake_0004.geometry} material={materials.AllTogetherBake} />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BaseGround_AllTogetherBake_0.geometry}
          material={materials.AllTogetherBake}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Hill_AllTogetherBake_0.geometry}
          material={materials.AllTogetherBake}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
      </group>
    </a.group>
  )
}

export default HillHouse