/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Shahriar Shahrabi (https://sketchfab.com/shahriyarshahrabi)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cabin-on-the-hill-7c6de91d44e14814be0297ce58af80f2
Title: Cabin on the hill
*/

import React, { useRef } from 'react';
import { useGLTF, useScroll } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';
import { a } from '@react-spring/three';
import HillCabinScene from '../assets/3d/hillCabin22.glb';

const HillCabin = ({ isRotating, setIsRotating, setCurrentStage, ...props }) => {
  const hillCabinRef = useRef();
  const scroll = useScroll(); 
  const { nodes, materials } = useGLTF(HillCabinScene);
  const lastStage = useRef(null);

  useFrame(() => {
    // 1. Smoothly rotate based on scroll progress
    const rotationAmount = scroll.offset * Math.PI * 2;
    
    if (hillCabinRef.current) {
      hillCabinRef.current.rotation.y = rotationAmount;
    }

    // 2. Linear Stage Detection
    // Since scroll.offset is always 0 to 1, we divide it into 4 equal sections
    // This ensures they always show up as 1 -> 2 -> 3 -> 4
    const scrollProgress = scroll.offset;
    let newStage = null;

    if (scrollProgress >= 0.02 && scrollProgress <= 0.22) {
    newStage = 1;
  } else if (scrollProgress >= 0.28 && scrollProgress <= 0.48) {
    newStage = 2;
  } else if (scrollProgress >= 0.52 && scrollProgress <= 0.72) {
    newStage = 3;
  } else if (scrollProgress >= 0.78 && scrollProgress <= 0.98) {
    newStage = 4;
  }

  if (newStage !== lastStage.current) {
    lastStage.current = newStage;
    setCurrentStage(newStage);
  }
});

  return (
    <a.group ref={hillCabinRef} {...props}>
      <mesh 
        castShadow 
        receiveShadow 
        geometry={nodes.Cube.geometry} 
        material={materials.Material} 
      />
      <group scale={0.01}>
        {/* Snow Particles */}
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh castShadow receiveShadow geometry={nodes.SnowParticles_SnowParticleTexture_0.geometry} material={materials.SnowParticleTexture} />
          <mesh castShadow receiveShadow geometry={nodes.SnowParticles_SnowParticleTexture_0001.geometry} material={materials.SnowParticleTexture} />
        </group>
        {/* Trees */}
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh castShadow receiveShadow geometry={nodes.Trees_VertexColor_0.geometry} material={materials.VertexColor} />
          <mesh castShadow receiveShadow geometry={nodes.Trees_VertexColor_0001.geometry} material={materials.VertexColor} />
          <mesh castShadow receiveShadow geometry={nodes.Trees_VertexColor_0002.geometry} material={materials.VertexColor} />
          <mesh castShadow receiveShadow geometry={nodes.Trees_VertexColor_0003.geometry} material={materials.VertexColor} />
        </group>
        <mesh castShadow receiveShadow geometry={nodes.Ground_VertexColor_0.geometry} material={materials.VertexColor} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh castShadow receiveShadow geometry={nodes.GroundTrees_VertexColor_0.geometry} material={materials.VertexColor} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh castShadow receiveShadow geometry={nodes.House_VertexColor_0.geometry} material={materials.VertexColor} position={[153.03, 1003.679, 452.871]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh castShadow receiveShadow geometry={nodes.MountainBased_SnowWithTexture_0.geometry} material={materials.SnowWithTexture} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh castShadow receiveShadow geometry={nodes.Snow_SnowWithTexture_0.geometry} material={materials.SnowWithTexture} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh castShadow receiveShadow geometry={nodes.TreeOutline_VertexColor_0.geometry} material={materials.VertexColor} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      </group>
    </a.group>
  );
};

export default HillCabin;